spring.datasource.url=jdbc:mysql://localhost:3306/restaurantdb
spring.datasource.username=root
spring.datasource.password=Hie&19061999
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
