CREATE TABLE IF NOT EXISTS `category` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` NVARCHAR(255) UNIQUE NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `item` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` NVARCHAR(255) UNIQUE NOT NULL,
    `description` TEXT,
    `image` NVARCHAR(255) UNIQUE ,
    `unit` NVARCHAR(255) NOT NULL,
    `price` FLOAT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `category_id` BIGINT NOT NULL,

    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS `bill` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `issued_at` TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `bill_item` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `bill_id` BIGINT NOT NULL,
    `item_id` BIGINT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_bill_id FOREIGN KEY (bill_id) REFERENCES bill(id),
    CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES item(id),
    CONSTRAINT uidx_bill_id_item_id UNIQUE (bill_id, item_id)
);

